services:
  quasar-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wagey-app
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - PORT=8000